[package]
name = "pick-e"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pick-e"
path = "src/main.rs"

[dependencies]
bevy = { version = "0.13.2", features = ["x11", "png"] }

bevy_rapier2d = "0.25" # This version of Rapier is designed for Bevy 0.13
bevy_embedded_assets = "0.10"

# Other dependencies
uuid = "1.8.1"
console_error_panic_hook = "0.1"
image = "0.24"
