[package]
name = "pick-e"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pick-e"
path = "src/main.rs"

[dependencies]
bevy = { version = "0.13.2", default-features = false, features = [
    "bevy_winit",
    "bevy_sprite",
    "bevy_render",
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_text",
    "bevy_ui",
    "x11",
    "png" 
] }

# This version of Rapier is designed for Bevy 0.13
bevy_rapier2d = "0.25"

# Other dependencies
uuid = "1.8.1"
console_error_panic_hook = "0.1"
image = "0.24"
