[package]
name = "pick-e"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy = { version = "0.13.2", default-features = false, features = [
    "webgl2",
    "bevy_winit",
    "bevy_sprite",
    "bevy_render",
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_text",
    "bevy_ui",
    "png" 
] }

bevy_rapier2d = "0.25"
bevy_embedded_assets = "0.10"

wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
uuid = { version = "1.8.1", features = ["js"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
image = "0.24"


