# Cargo_native.toml

[package]
name = "pick-e"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pick-e"
path = "src/main.rs"

[dependencies]
bevy = { version = "0.16.1", default-features = false, features = [
    "bevy_winit",
    "bevy_sprite",
    "bevy_render",
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_text",
    "bevy_ui",
    "bevy_log",
    "x11"
] }

uuid = "1.8.1"
console_error_panic_hook = "0.1"
